name: turbopy
channels:
        - defaults
dependencies:
        - python=3.7
        - numpy
        - scipy
        - xarray
        - pytest-runner
        - pytest
        - pytest-cov
        - sphinx
        - pip
        - pip:
                - qtoml
                - livereload
                - formic2
                - sphobjinv
